//Teste de requisições REST - Alunos

@baseURL = http://localhost:4000/api

@matricula = 1234

###
// GET - Lista todos os alunos
GET {{baseURL}}/alunos
Content-Type: application/json

###
// GET - Lista apenas alunos pela matrícula
GET {{baseURL}}/alunos/{{matricula}}
Content-Type: application/json

###
// POST - Inclui um novo aluno
POST {{baseURL}}/alunos
Content-Type: application/json

{
    "matricula": 1234,
    "nome": "Letícia",
    "curso": "Medicina",
    "genero": "Masculino",
    "nascimento": "2003-04-30",
    "rg": "12.456.878-7",
    "email": "teste3@gmail.com",
    "celular": "15-99445-1484"
}

###
// PUT - Altera um aluno existente
PUT {{baseURL}}/alunos
Content-Type: application/json

{
    "matricula": 1234510,
    "nome": "Sara",
    "curso": "MEDICINA",
    "genero": "Feminino",
    "nascimento": "2000-05-14",
    "rg": "12.355.878-7",
    "email": "teste@gmail.com",
    "celular": "15-99415-1234"
}

###
// DELETE - Apaga um aluno através da matrícula
DELETE {{baseURL}}/alunos/{{matricula}}
Content-Type: application/json